using System.Diagnostics;
using System.IO;
using System.Text;
using System.Windows;
using ADMX2Reg.Core;
using ADMX2Reg.Core.Admx;
using ADMX2Reg.Core.Gpo;
using ADMX2Reg.Core.Registry;
using ADMX2Reg.Services;
using ADMX2Reg.ViewModels;
using Microsoft.Win32;
using Wpf.Ui.Controls;

namespace ADMX2Reg.Views;

/// <summary>Export dialog: format, scopes, live preview and compile warnings.</summary>
public partial class ExportWindow : FluentWindow {
    private readonly GpoDocument _gpo;
    private readonly AdmxCatalog _catalog;
    private readonly AppSettings _settings;
    private readonly Dictionary<PolicyScope, IReadOnlyList<RegistryOperation>> _ops = [];
    private string _text = "";

    internal ExportWindow(GpoDocument gpo, AdmxCatalog catalog, AppSettings settings) {
        InitializeComponent();
        _gpo = gpo;
        _catalog = catalog;
        _settings = settings;
        Bar.Title = $"Export '{gpo.Name}'";
        Title = Bar.Title;
        FormatBox.SelectedIndex = 0;
    }

    private bool IncludeComputer => ComputerCheck.IsChecked == true;
    private bool IncludeUser => UserCheck.IsChecked == true;

    private IEnumerable<PolicyScope> SelectedScopes() {
        if (IncludeComputer) {
            yield return PolicyScope.Computer;
        }
        if (IncludeUser) {
            yield return PolicyScope.User;
        }
    }

    private string Header => $"Generated by ADMX2Reg from GPO '{_gpo.Name}' on {DateTime.Now:yyyy-MM-dd HH:mm}";

    private void Options_Changed(object sender, RoutedEventArgs e) {
        if (!IsLoaded && FormatBox.SelectedIndex < 0) {
            return;
        }
        Refresh();
    }

    private void Refresh() {
        var warnings = new List<string>();
        _ops.Clear();
        try {
            foreach (var scope in SelectedScopes()) {
                var result = GpoCompiler.Compile(_gpo, _catalog, scope);
                _ops[scope] = result.Operations;
                var prefix = scope == PolicyScope.Computer ? "Computer: " : "User: ";
                warnings.AddRange(result.Warnings.Select(w => prefix + w));
            }

            var all = _ops.Values.SelectMany(o => o).ToList();
            using var writer = new StringWriter();
            switch (FormatBox.SelectedIndex) {
                case 0:
                    RegFileWriter.Write(all, writer, Header);
                    break;
                case 1:
                    PowerShellWriter.Write(all, writer, PowerShellStyle.Standalone, Header);
                    break;
                case 2:
                    PowerShellWriter.Write(all, writer, PowerShellStyle.Minimal, Header);
                    break;
                default:
                    writer.WriteLine("Registry.pol is a binary format. The files below will be written to the chosen folder:");
                    writer.WriteLine();
                    foreach (var (scope, ops) in _ops) {
                        writer.WriteLine($"  {PolFolder(scope)}\\Registry.pol : {ops.Count} registry operation(s)");
                    }
                    break;
            }
            _text = writer.ToString();
        } catch (Exception ex) {
            _text = $"Preview failed: {ex.Message}";
            warnings.Add(ex.Message);
        }

        PreviewBox.Text = _text;
        WarningsList.ItemsSource = warnings;
        WarningsList.Visibility = warnings.Count == 0 ? Visibility.Collapsed : Visibility.Visible;
        WarningsHeader.Visibility = WarningsList.Visibility;
        ExportButton.IsEnabled = _ops.Count > 0;
    }

    private static string PolFolder(PolicyScope scope) => scope == PolicyScope.Computer ? "Machine" : "User";

    private void Export_Click(object sender, RoutedEventArgs e) {
        try {
            var target = FormatBox.SelectedIndex == 3 ? ExportPol() : ExportFile();
            if (target == null) {
                return;
            }
            _settings.LastExportFolder = Directory.Exists(target) ? target : Path.GetDirectoryName(target);
            _settings.Save();
            var answer = Dialogs.Show("Export complete", $"Exported to:{Environment.NewLine}{target}", "OK", "Open folder");
            if (answer == 1) {
                var args = Directory.Exists(target) ? $"\"{target}\"" : $"/select,\"{target}\"";
                Process.Start(new ProcessStartInfo("explorer.exe", args) { UseShellExecute = true });
            }
        } catch (Exception ex) {
            Dialogs.Error("Export failed", ex.Message);
        }
    }

    private string? ExportFile() {
        var isReg = FormatBox.SelectedIndex == 0;
        var dialog = new SaveFileDialog {
            Title = "Export",
            Filter = isReg ? "Registry file (*.reg)|*.reg" : "PowerShell script (*.ps1)|*.ps1",
            FileName = MainViewModel.SafeFileName(_gpo.Name) + (isReg ? ".reg" : ".ps1"),
            InitialDirectory = MainViewModel.FolderOrNull(_settings.LastExportFolder) ?? ""
        };
        if (dialog.ShowDialog(this) != true) {
            return null;
        }
        // .reg: UTF-16 LE with BOM like regedit. .ps1: UTF-8 with BOM so Windows PowerShell 5.1 reads non-ASCII correctly.
        File.WriteAllText(dialog.FileName, _text, isReg ? Encoding.Unicode : new UTF8Encoding(true));
        return dialog.FileName;
    }

    private string? ExportPol() {
        var dialog = new OpenFolderDialog {
            Title = "Choose a folder for the Machine and User Registry.pol files",
            InitialDirectory = MainViewModel.FolderOrNull(_settings.LastExportFolder) ?? ""
        };
        if (dialog.ShowDialog(this) != true) {
            return null;
        }
        var written = 0;
        foreach (var (scope, ops) in _ops) {
            if (ops.Count == 0) {
                continue;
            }
            var folder = Path.Combine(dialog.FolderName, PolFolder(scope));
            Directory.CreateDirectory(folder);
            using var stream = File.Create(Path.Combine(folder, "Registry.pol"));
            PolFileWriter.Write(ops, stream);
            written++;
        }
        if (written == 0) {
            Dialogs.Info("Export", "There were no registry operations to write.");
            return null;
        }
        return dialog.FolderName;
    }
}
