using System.Globalization;
using System.Text;
using ADMX2Reg.Core.Registry;

namespace ADMX2Reg.Core;

/// <remarks>
/// The script contains non-ASCII text literally, so the caller should save it as UTF-8 with BOM
/// (Windows PowerShell 5.1 reads BOM-less files as the ANSI code page).
/// </remarks>
public static partial class PowerShellWriter {
    public static partial void Write(IEnumerable<RegistryOperation> operations, TextWriter writer, PowerShellStyle style, string? headerComment) {
        var ops = operations.ToList();
        var w = new ScriptBuilder(writer);
        if (style == PowerShellStyle.Minimal) {
            WriteMinimal(ops, w, headerComment);
        } else {
            WriteStandalone(ops, w, headerComment);
        }
    }

    // ------------------------------------------------------------------ Minimal

    private static void WriteMinimal(List<RegistryOperation> ops, ScriptBuilder w, string? headerComment) {
        w.Line("# Registry settings generated by ADMX2Reg on " + Timestamp());
        foreach (var line in CommentLines(headerComment)) {
            w.Line("# " + line);
        }
        w.Line("# Settings under HKCU apply to the user running this script. Settings under HKLM require an elevated session.");

        string? ensured = null; // key already guarded by the previous command
        foreach (var op in ops) {
            var sameKey = ensured != null && string.Equals(ensured, PsPath(op), StringComparison.OrdinalIgnoreCase);
            if (!sameKey) {
                w.Blank();
            }
            ensured = op.Kind is RegistryOperationKind.SetValue or RegistryOperationKind.CreateKey ? PsPath(op) : null;
            var path = Literal(PsPath(op));
            switch (op.Kind) {
                case RegistryOperationKind.SetValue:
                    if (!sameKey) {
                        EmitKeyGuard(w, path);
                    }
                    w.Line($"New-ItemProperty -LiteralPath {path} -Name {Literal(CmdletName(op.ValueName))} -PropertyType {PropertyType(op.Type)} -Value {ValueExpression(op)} -Force | Out-Null");
                    break;
                case RegistryOperationKind.CreateKey:
                    if (!sameKey) {
                        EmitKeyGuard(w, path);
                    }
                    break;
                case RegistryOperationKind.DeleteValue:
                    if (string.IsNullOrEmpty(op.ValueName)) {
                        // Remove-ItemProperty cannot remove the unnamed default value, the .NET API can.
                        w.Line($"$key = {HiveClass(op.Hive)}.OpenSubKey({Literal(op.Key)}, $true)");
                        w.Line("if ($null -ne $key) {");
                        w.Line("    $key.DeleteValue('', $false)");
                        w.Line("    $key.Close()");
                        w.Line("}");
                    } else {
                        w.Line($"Remove-ItemProperty -LiteralPath {path} -Name {Literal(op.ValueName)} -ErrorAction SilentlyContinue");
                    }
                    break;
                case RegistryOperationKind.DeleteAllValues:
                    w.Line($"$key = {HiveClass(op.Hive)}.OpenSubKey({Literal(op.Key)}, $true)");
                    w.Line("if ($null -ne $key) {");
                    w.Line("    foreach ($name in $key.GetValueNames()) {");
                    w.Line("        $key.DeleteValue($name)");
                    w.Line("    }");
                    w.Line("");
                    w.Line("    $key.Close()");
                    w.Line("}");
                    break;
                case RegistryOperationKind.DeleteKey:
                    w.Line($"if (Test-Path -LiteralPath {path}) {{");
                    w.Line($"    Remove-Item -LiteralPath {path} -Recurse -Force");
                    w.Line("}");
                    break;
            }
        }
    }

    /// <summary>New-Item -Force on an existing registry key wipes its values, so only create when missing.</summary>
    private static void EmitKeyGuard(ScriptBuilder w, string path) {
        w.Line($"if (-not (Test-Path -LiteralPath {path})) {{");
        w.Line($"    New-Item -Path {path} -Force | Out-Null");
        w.Line("}");
    }

    // ------------------------------------------------------------------ Standalone

    private static void WriteStandalone(List<RegistryOperation> ops, ScriptBuilder w, string? headerComment) {
        var needsAdmin = ops.Any(o => o.Hive == RegistryHive.LocalMachine);

        w.Line("<#");
        w.Line(".SYNOPSIS");
        w.Line("    Applies registry settings generated from Group Policy templates.");
        w.Blank();
        w.Line(".DESCRIPTION");
        w.Line("    Sets, deletes and clears registry values and keys the same way the matching Group Policy settings would.");
        w.Line("    The script is idempotent: values that already match are left alone. Use -WhatIf to preview changes");
        w.Line("    and -Verbose to see every action.");
        w.Blank();
        w.Line(".NOTES");
        if (string.IsNullOrWhiteSpace(headerComment)) {
            w.Line("    Generated by ADMX2Reg on " + Timestamp() + ".");
        }
        foreach (var line in CommentLines(headerComment)) {
            w.Line("    " + line.Replace("#>", "# >"));
        }
        w.Line(needsAdmin
            ? "    HKLM settings require an elevated session. HKCU settings apply to the user running the script."
            : "    HKCU settings apply to the user running the script.");
        w.Line("#>");
        w.Line("[CmdletBinding(SupportsShouldProcess = $true)]");
        w.Line("param()");
        w.Blank();
        w.Line("Set-StrictMode -Version 2.0");
        w.Line("$ErrorActionPreference = 'Stop'");

        if (needsAdmin) {
            w.Blank();
            w.Line("$identity = [System.Security.Principal.WindowsIdentity]::GetCurrent()");
            w.Line("$principal = New-Object -TypeName System.Security.Principal.WindowsPrincipal -ArgumentList $identity");
            w.Line("if (-not $principal.IsInRole([System.Security.Principal.WindowsBuiltInRole]::Administrator)) {");
            w.Line("    throw 'This script changes HKEY_LOCAL_MACHINE and must run in an elevated PowerShell session (Run as administrator).'");
            w.Line("}");
        }

        foreach (var line in StandaloneHelpers.Split('\n')) {
            w.Line(line.TrimEnd('\r'));
        }

        w.Blank();
        w.Line("# ---- Settings ----");
        foreach (var op in ops) {
            var path = Literal(PsPath(op));
            switch (op.Kind) {
                case RegistryOperationKind.SetValue:
                    w.Line($"Set-PolicyRegistryValue -Path {path} -Name {Literal(op.ValueName ?? "")} -Kind {PropertyType(op.Type)} -Value {ValueExpression(op)}");
                    break;
                case RegistryOperationKind.CreateKey:
                    w.Line($"New-PolicyRegistryKey -Path {path}");
                    break;
                case RegistryOperationKind.DeleteValue:
                    w.Line($"Remove-PolicyRegistryValue -Path {path} -Name {Literal(op.ValueName ?? "")}");
                    break;
                case RegistryOperationKind.DeleteAllValues:
                    w.Line($"Clear-PolicyRegistryKey -Path {path}");
                    break;
                case RegistryOperationKind.DeleteKey:
                    w.Line($"Remove-PolicyRegistryKey -Path {path}");
                    break;
            }
        }

        w.Blank();
        w.Line("Write-Output ('Done. Changed: {0}, Unchanged: {1}, Failed: {2}.' -f $Result.Changed, $Result.Unchanged, $Result.Failed)");
        w.Line("if ($Result.Failed -gt 0) {");
        w.Line("    exit 1");
        w.Line("}");
    }

    private const string StandaloneHelpers = """

        $Result = @{
            Changed   = 0
            Unchanged = 0
            Failed    = 0
        }

        function Get-PolicyRegistryValueInfo {
            [CmdletBinding()]
            param(
                [Parameter(Mandatory = $true)]
                [string]$Path,

                [Parameter(Mandatory = $true)]
                [AllowEmptyString()]
                [string]$Name
            )

            $key = Get-Item -LiteralPath $Path -ErrorAction SilentlyContinue
            if ($null -eq $key) {
                return $null
            }

            try {
                if ($key.GetValueNames() -notcontains $Name) {
                    return $null
                }

                [pscustomobject]@{
                    Kind  = $key.GetValueKind($Name)
                    Value = $key.GetValue($Name, $null, [Microsoft.Win32.RegistryValueOptions]::DoNotExpandEnvironmentNames)
                }
            } finally {
                $key.Close()
            }
        }

        function Test-PolicyValueEqual {
            [CmdletBinding()]
            [OutputType([bool])]
            param(
                [AllowNull()]
                $Current,

                [AllowNull()]
                $Expected
            )

            if ($Expected -is [System.Array]) {
                if (-not ($Current -is [System.Array]) -or $Current.Length -ne $Expected.Length) {
                    return $false
                }

                for ($i = 0; $i -lt $Expected.Length; $i++) {
                    if ($Current[$i] -cne $Expected[$i]) {
                        return $false
                    }
                }

                return $true
            }

            return ($Current -ceq $Expected)
        }

        function Invoke-PolicyRegistryValueDelete {
            [CmdletBinding()]
            param(
                [Parameter(Mandatory = $true)]
                [string]$Path,

                [Parameter(Mandatory = $true)]
                [AllowEmptyString()]
                [string]$Name
            )

            # The .NET API is the only way to remove the unnamed default value.
            $hive = if ($Path.StartsWith('HKLM:', [System.StringComparison]::OrdinalIgnoreCase)) {
                [Microsoft.Win32.Registry]::LocalMachine
            } else {
                [Microsoft.Win32.Registry]::CurrentUser
            }

            $key = $hive.OpenSubKey($Path.Substring(6), $true)
            if ($null -ne $key) {
                try {
                    $key.DeleteValue($Name, $false)
                } finally {
                    $key.Close()
                }
            }
        }

        function New-PolicyRegistryKey {
            [CmdletBinding(SupportsShouldProcess = $true)]
            param(
                [Parameter(Mandatory = $true)]
                [string]$Path
            )

            try {
                if (Test-Path -LiteralPath $Path) {
                    Write-Verbose "Key exists: $Path"
                    $Result.Unchanged++

                    return
                }

                if ($PSCmdlet.ShouldProcess($Path, 'Create key')) {
                    New-Item -Path $Path -Force | Out-Null
                    Write-Verbose "Created key: $Path"
                }

                $Result.Changed++
            } catch {
                Write-Warning "Failed to create key '$Path': $($_.Exception.Message)"
                $Result.Failed++
            }
        }

        function Set-PolicyRegistryValue {
            [CmdletBinding(SupportsShouldProcess = $true)]
            param(
                [Parameter(Mandatory = $true)]
                [string]$Path,

                [Parameter(Mandatory = $true)]
                [AllowEmptyString()]
                [string]$Name,

                [Parameter(Mandatory = $true)]
                [Microsoft.Win32.RegistryValueKind]$Kind,

                [AllowNull()]
                $Value
            )

            $label = if ($Name -eq '') { '(default)' } else { $Name }

            try {
                $expected = $Value
                if ($Kind -eq 'DWord') {
                    $expected = [System.BitConverter]::ToInt32([System.BitConverter]::GetBytes([uint32]$Value), 0)
                } elseif ($Kind -eq 'QWord') {
                    $expected = [System.BitConverter]::ToInt64([System.BitConverter]::GetBytes([uint64]$Value), 0)
                } elseif ($Kind -eq 'None') {
                    $expected = [byte[]]@()
                }

                $info = Get-PolicyRegistryValueInfo -Path $Path -Name $Name
                if ($null -ne $info -and $info.Kind -eq $Kind -and (Test-PolicyValueEqual -Current $info.Value -Expected $expected)) {
                    Write-Verbose "Unchanged: $Path\$label"
                    $Result.Unchanged++

                    return
                }

                if ($PSCmdlet.ShouldProcess("$Path\$label", "Set $Kind value")) {
                    if (-not (Test-Path -LiteralPath $Path)) {
                        New-Item -Path $Path -Force | Out-Null
                    }

                    New-ItemProperty -LiteralPath $Path -Name $(if ($Name -eq '') { '(default)' } else { $Name }) -PropertyType $Kind -Value $Value -Force | Out-Null
                    Write-Verbose "Set $Kind value: $Path\$label"
                }

                $Result.Changed++
            } catch {
                Write-Warning "Failed to set '$Path\$label': $($_.Exception.Message)"
                $Result.Failed++
            }
        }

        function Remove-PolicyRegistryValue {
            [CmdletBinding(SupportsShouldProcess = $true)]
            param(
                [Parameter(Mandatory = $true)]
                [string]$Path,

                [Parameter(Mandatory = $true)]
                [AllowEmptyString()]
                [string]$Name
            )

            $label = if ($Name -eq '') { '(default)' } else { $Name }

            try {
                if ($null -eq (Get-PolicyRegistryValueInfo -Path $Path -Name $Name)) {
                    Write-Verbose "Already absent: $Path\$label"
                    $Result.Unchanged++

                    return
                }

                if ($PSCmdlet.ShouldProcess("$Path\$label", 'Remove value')) {
                    Invoke-PolicyRegistryValueDelete -Path $Path -Name $Name
                    Write-Verbose "Removed value: $Path\$label"
                }

                $Result.Changed++
            } catch {
                Write-Warning "Failed to remove '$Path\$label': $($_.Exception.Message)"
                $Result.Failed++
            }
        }

        function Clear-PolicyRegistryKey {
            [CmdletBinding(SupportsShouldProcess = $true)]
            param(
                [Parameter(Mandatory = $true)]
                [string]$Path
            )

            try {
                $key = Get-Item -LiteralPath $Path -ErrorAction SilentlyContinue
                $names = @()
                if ($null -ne $key) {
                    $names = @($key.GetValueNames())
                    $key.Close()
                }

                if ($names.Count -eq 0) {
                    Write-Verbose "No values to clear: $Path"
                    $Result.Unchanged++

                    return
                }

                if ($PSCmdlet.ShouldProcess($Path, 'Remove all values')) {
                    foreach ($name in $names) {
                        Invoke-PolicyRegistryValueDelete -Path $Path -Name $name
                    }

                    Write-Verbose "Cleared $($names.Count) value(s): $Path"
                }

                $Result.Changed++
            } catch {
                Write-Warning "Failed to clear '$Path': $($_.Exception.Message)"
                $Result.Failed++
            }
        }

        function Remove-PolicyRegistryKey {
            [CmdletBinding(SupportsShouldProcess = $true)]
            param(
                [Parameter(Mandatory = $true)]
                [string]$Path
            )

            try {
                if (-not (Test-Path -LiteralPath $Path)) {
                    Write-Verbose "Already absent: $Path"
                    $Result.Unchanged++

                    return
                }

                if ($PSCmdlet.ShouldProcess($Path, 'Remove key and all subkeys')) {
                    Remove-Item -LiteralPath $Path -Recurse -Force
                    Write-Verbose "Removed key: $Path"
                }

                $Result.Changed++
            } catch {
                Write-Warning "Failed to remove key '$Path': $($_.Exception.Message)"
                $Result.Failed++
            }
        }
        """;

    // ------------------------------------------------------------------ helpers

    private static string Timestamp() => DateTime.Now.ToString("yyyy-MM-dd HH:mm", CultureInfo.InvariantCulture);

    private static IEnumerable<string> CommentLines(string? comment) =>
        string.IsNullOrEmpty(comment) ? [] : comment.Split(["\r\n", "\n", "\r"], StringSplitOptions.None);

    private static string PsPath(RegistryOperation op) {
        var drive = op.Hive == RegistryHive.LocalMachine ? "HKLM:" : "HKCU:";
        return string.IsNullOrEmpty(op.Key) ? drive + "\\" : drive + "\\" + op.Key;
    }

    private static string HiveClass(RegistryHive hive) =>
        hive == RegistryHive.LocalMachine ? "[Microsoft.Win32.Registry]::LocalMachine" : "[Microsoft.Win32.Registry]::CurrentUser";

    /// <summary>The registry provider addresses the default value as "(default)".</summary>
    private static string CmdletName(string? name) => string.IsNullOrEmpty(name) ? "(default)" : name;

    private static string PropertyType(RegValueType type) => type switch {
        RegValueType.String => "String",
        RegValueType.ExpandString => "ExpandString",
        RegValueType.DWord => "DWord",
        RegValueType.QWord => "QWord",
        RegValueType.MultiString => "MultiString",
        RegValueType.Binary => "Binary",
        _ => "None"
    };

    private static string ValueExpression(RegistryOperation op) {
        switch (op.Type) {
            case RegValueType.String:
            case RegValueType.ExpandString:
                return Literal(op.Data as string ?? "");
            case RegValueType.DWord:
                return Convert.ToUInt32(op.Data, CultureInfo.InvariantCulture).ToString(CultureInfo.InvariantCulture);
            case RegValueType.QWord: {
                var n = Convert.ToUInt64(op.Data, CultureInfo.InvariantCulture);
                var text = n.ToString(CultureInfo.InvariantCulture);
                return n > long.MaxValue ? "([uint64]" + text + ")" : text;
            }
            case RegValueType.MultiString: {
                var items = (op.Data as string[] ?? []).Select(Literal);
                return "([string[]]@(" + string.Join(", ", items) + "))";
            }
            case RegValueType.Binary: {
                var bytes = (op.Data as byte[] ?? []).Select(b => "0x" + b.ToString("x2", CultureInfo.InvariantCulture));
                return "([byte[]]@(" + string.Join(", ", bytes) + "))";
            }
            default:
                return "([byte[]]@())";
        }
    }

    /// <summary>
    /// A PowerShell string expression. Plain text becomes a single-quoted literal ('' escapes quotes). Characters that
    /// PowerShell treats as quotes (typographic single quotes) or that are control characters are spliced in as [char] codes.
    /// </summary>
    private static string Literal(string s) {
        var parts = new List<string>();
        var sb = new StringBuilder();

        void FlushText() {
            if (sb.Length > 0) {
                parts.Add("'" + sb + "'");
                sb.Clear();
            }
        }

        foreach (var c in s) {
            if (c == '\'') {
                sb.Append("''");
            } else if (c < 0x20 || c == 0x7f || c == 0x85 || c == 0x2028 || c == 0x2029 || (c >= 0x2018 && c <= 0x201B)) {
                FlushText();
                parts.Add("[char]0x" + ((int)c).ToString("x4", CultureInfo.InvariantCulture));
            } else {
                sb.Append(c);
            }
        }
        FlushText();

        if (parts.Count == 0) {
            return "''";
        }
        if (parts.Count == 1 && parts[0][0] == '\'') {
            return parts[0];
        }
        // A leading [char] needs a string on the left so + concatenates instead of adding numbers.
        if (parts[0][0] != '\'') {
            parts.Insert(0, "''");
        }
        return "(" + string.Join(" + ", parts) + ")";
    }

    private sealed class ScriptBuilder(TextWriter writer) {
        private bool _lastBlank = true;

        public void Line(string text) {
            writer.Write(text);
            writer.Write("\r\n");
            _lastBlank = text.Length == 0;
        }

        public void Blank() {
            if (!_lastBlank) {
                Line("");
            }
        }
    }
}
