using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.Text;
using ADMX2Reg.Core;
using ADMX2Reg.Core.Admx;
using ADMX2Reg.Core.Gpo;
using ADMX2Reg.Core.Registry;
using ADMX2Reg.ViewModels;
using Microsoft.Win32;

namespace ADMX2Reg.Services;

public enum ExportFormat {
    Reg,
    PowerShell,
    PowerShellMinimal,
    RegistryPol
}

public sealed record ExportPreviewResult(
    string Text,
    IReadOnlyList<string> Warnings,
    IReadOnlyList<(PolicyScope Scope, IReadOnlyList<RegistryOperation> Operations)> Operations);

/// <summary>Builds the live export preview of a whole GPO and saves it, using the same writers as the Export window.</summary>
public static class ExportPreviewBuilder {
    public static string PolFolder(PolicyScope scope) => scope == PolicyScope.Computer ? "Machine" : "User";

    public static ExportPreviewResult Build(GpoDocument gpo, AdmxCatalog catalog, bool computer, bool user, ExportFormat format) {
        var warnings = new List<string>();
        var ops = new List<(PolicyScope, IReadOnlyList<RegistryOperation>)>();
        string text;
        try {
            var scopes = new List<PolicyScope>();
            if (computer) {
                scopes.Add(PolicyScope.Computer);
            }
            if (user) {
                scopes.Add(PolicyScope.User);
            }
            foreach (var scope in scopes) {
                var result = GpoCompiler.Compile(gpo, catalog, scope);
                ops.Add((scope, result.Operations));
                var prefix = scope == PolicyScope.Computer ? "Computer: " : "User: ";
                warnings.AddRange(result.Warnings.Select(w => prefix + w));
            }

            var header = $"Generated by ADMX2Reg from GPO '{gpo.Name}' on {DateTime.Now:yyyy-MM-dd HH:mm}";
            var all = ops.SelectMany(o => o.Item2).ToList();
            using var writer = new StringWriter();
            switch (format) {
                case ExportFormat.Reg:
                    RegFileWriter.Write(all, writer, header);
                    break;
                case ExportFormat.PowerShell:
                    PowerShellWriter.Write(all, writer, PowerShellStyle.Standalone, header);
                    break;
                case ExportFormat.PowerShellMinimal:
                    PowerShellWriter.Write(all, writer, PowerShellStyle.Minimal, header);
                    break;
                default:
                    WritePolListing(writer, ops);
                    break;
            }
            text = writer.ToString();
        } catch (Exception ex) {
            text = $"Preview failed: {ex.Message}";
            warnings.Add(ex.Message);
        }
        return new ExportPreviewResult(text, warnings, ops);
    }

    // ------------------------------------------------------------------ Registry.pol listing

    private static void WritePolListing(StringWriter writer, List<(PolicyScope Scope, IReadOnlyList<RegistryOperation> Operations)> ops) {
        if (ops.Count == 0) {
            writer.WriteLine("Registry.pol preview (binary file): no scope selected");
            return;
        }
        writer.WriteLine("Registry.pol preview (binary file): " + string.Join(", ",
            ops.Select(o => $"{o.Operations.Count} {(o.Operations.Count == 1 ? "entry" : "entries")} ({PolFolder(o.Scope)})")));
        foreach (var (scope, operations) in ops) {
            writer.WriteLine();
            writer.WriteLine($"{PolFolder(scope)}\\Registry.pol");
            foreach (var op in operations) {
                writer.WriteLine(PolEntry(op));
            }
        }
    }

    /// <summary>One line per Registry.pol entry, mirroring what <see cref="PolFileWriter"/> writes.</summary>
    internal static string PolEntry(RegistryOperation op) {
        switch (op.Kind) {
            case RegistryOperationKind.SetValue:
                return $"[{op.Key};{op.ValueName ?? ""};{PolType(op.Type)};{PolData(op)}]";
            case RegistryOperationKind.DeleteValue:
                return $"[{op.Key};**del.{op.ValueName};REG_SZ; ]";
            case RegistryOperationKind.DeleteAllValues:
                return $"[{op.Key};**delvals.;REG_SZ; ]";
            case RegistryOperationKind.DeleteKey: {
                var slash = op.Key.LastIndexOf('\\');
                var parent = slash < 0 ? "" : op.Key[..slash];
                var child = slash < 0 ? op.Key : op.Key[(slash + 1)..];
                return $"[{parent};**DeleteKeys;REG_SZ;{child}]";
            }
            default:
                return $"[{op.Key};;REG_NONE;]";
        }
    }

    private static string PolType(RegValueType type) => type switch {
        RegValueType.String => "REG_SZ",
        RegValueType.ExpandString => "REG_EXPAND_SZ",
        RegValueType.DWord => "REG_DWORD",
        RegValueType.QWord => "REG_QWORD",
        RegValueType.MultiString => "REG_MULTI_SZ",
        RegValueType.Binary => "REG_BINARY",
        _ => "REG_NONE"
    };

    private static string PolData(RegistryOperation op) => op.Type switch {
        RegValueType.String or RegValueType.ExpandString => op.Data as string ?? "",
        RegValueType.DWord or RegValueType.QWord => Convert.ToString(op.Data, CultureInfo.InvariantCulture) ?? "",
        RegValueType.MultiString => string.Join("|", op.Data as string[] ?? []),
        RegValueType.Binary => BitConverter.ToString(op.Data as byte[] ?? []).Replace('-', ','),
        _ => ""
    };

    // ------------------------------------------------------------------ saving

    /// <summary>Saves the preview in the given format after asking where. Returns the written file or folder, or null when cancelled.</summary>
    public static string? Save(GpoDocument gpo, ExportPreviewResult preview, ExportFormat format, AppSettings settings) {
        var target = format == ExportFormat.RegistryPol ? SavePol(preview, settings) : SaveFile(gpo, preview, format, settings);
        if (target == null) {
            return null;
        }
        settings.LastExportFolder = Directory.Exists(target) ? target : Path.GetDirectoryName(target);
        settings.Save();
        var answer = Dialogs.Show("Export complete", $"Exported to:{Environment.NewLine}{target}", "OK", "Open folder");
        if (answer == 1) {
            var args = Directory.Exists(target) ? $"\"{target}\"" : $"/select,\"{target}\"";
            Process.Start(new ProcessStartInfo("explorer.exe", args) { UseShellExecute = true });
        }
        return target;
    }

    private static string? SaveFile(GpoDocument gpo, ExportPreviewResult preview, ExportFormat format, AppSettings settings) {
        var isReg = format == ExportFormat.Reg;
        var dialog = new SaveFileDialog {
            Title = "Export",
            Filter = isReg ? "Registry file (*.reg)|*.reg" : "PowerShell script (*.ps1)|*.ps1",
            FileName = MainViewModel.SafeFileName(gpo.Name) + (isReg ? ".reg" : ".ps1"),
            InitialDirectory = MainViewModel.FolderOrNull(settings.LastExportFolder) ?? ""
        };
        if (dialog.ShowDialog(Dialogs.Owner) != true) {
            return null;
        }
        // .reg: UTF-16 LE with BOM like regedit. .ps1: UTF-8 with BOM so Windows PowerShell 5.1 reads non-ASCII correctly.
        File.WriteAllText(dialog.FileName, preview.Text, isReg ? Encoding.Unicode : new UTF8Encoding(true));
        return dialog.FileName;
    }

    private static string? SavePol(ExportPreviewResult preview, AppSettings settings) {
        var dialog = new OpenFolderDialog {
            Title = "Choose a folder for the Machine and User Registry.pol files",
            InitialDirectory = MainViewModel.FolderOrNull(settings.LastExportFolder) ?? ""
        };
        if (dialog.ShowDialog(Dialogs.Owner) != true) {
            return null;
        }
        var written = 0;
        foreach (var (scope, ops) in preview.Operations) {
            if (ops.Count == 0) {
                continue;
            }
            var folder = Path.Combine(dialog.FolderName, PolFolder(scope));
            Directory.CreateDirectory(folder);
            using var stream = File.Create(Path.Combine(folder, "Registry.pol"));
            PolFileWriter.Write(ops, stream);
            written++;
        }
        if (written == 0) {
            Dialogs.Info("Export", "There were no registry operations to write.");
            return null;
        }
        return dialog.FolderName;
    }
}
